# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Plant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Plant.proto',
  package='dfproto',
  syntax='proto2',
  serialized_pb=_b('\n\x0bPlant.proto\x12\x07\x64\x66proto\"A\n\x05Plant\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12\x10\n\x08is_shrub\x18\x03 \x02(\x08\x12\x10\n\x08material\x18\x04 \x01(\rB\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLANT = _descriptor.Descriptor(
  name='Plant',
  full_name='dfproto.Plant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='dfproto.Plant.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='dfproto.Plant.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_shrub', full_name='dfproto.Plant.is_shrub', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='dfproto.Plant.material', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Plant'] = _PLANT

Plant = _reflection.GeneratedProtocolMessageType('Plant', (_message.Message,), dict(
  DESCRIPTOR = _PLANT,
  __module__ = 'Plant_pb2'
  # @@protoc_insertion_point(class_scope:dfproto.Plant)
  ))
_sym_db.RegisterMessage(Plant)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
